import{a as m,S as y,i as a}from"./assets/vendor-D9tHNiur.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const l=document.querySelector(".loader"),g="49108908-dee8565c8232193f8d4c70c7a",h="https://pixabay.com/api/";function b(){l.style.display="inline-block"}function L(){l.style.display="none"}function S(s){b();const o={key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return m.get(h,{params:o}).then(r=>r.data.hits).catch(r=>(console.error("Помилка під час запиту:",r),[])).finally(()=>{L()})}const c=document.querySelector(".gallery");c.classList.add("gallery-style");function $(s){const o=s.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:u,comments:f,downloads:d})=>`<li class="gallery-item">
    <a class="gallery-link" href="${e}">
      <img class="gallery-image" src="${i}" alt="${t}" />
    </a>
    <div class="info">
      <p class="info-item"><b>Likes</b> <span>${n}</span></p>
      <p class="info-item"><b>Views</b> <span>${u}</span></p>
      <p class="info-item"><b>Comments</b> <span>${f}</span></p>
      <p class="info-item"><b>Downloads</b> <span>${d}</span></p>
    </div>
  </li>`).join("");c.innerHTML=o,new y(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"}).refresh()}const p=document.querySelector(".search-form"),v=document.querySelector(".gallery");p.addEventListener("submit",q);function q(s){s.preventDefault();const o=s.currentTarget.elements.search.value.trim();if(!o){a.error({title:"Введіть у полі пошуку яке зображення Вас цікавить.",message:"",position:"topCenter"});return}v.innerHTML="",S(o).then(r=>{if(r.length===0){a.error({title:"Пошук не дав результатів. Будь ласка, спроуйте ще!",message:"",position:"topCenter"});return}$(r)}).catch(r=>{console.error("Під час запиту сталася наступна помилка:",r),a.error({title:"Сталася помилка! Повторіть спробу пізніше.",message:`${r}`,position:"topCenter"})}),p.reset()}
//# sourceMappingURL=index.js.map
